stages:
  - test
  - compile
  - release

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

before_script:
  - npm install --save-dev

test_job:
  stage: test
  script:
    - npm run test
  tags:
    - master
    - develop

build_job:
  stage: compile
  script:
    - npm run build
    - npm publish
  only:
    - master
  tags:
    - master
