stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - esm/*
    - umd/*

before_script:
  - npm install --save-dev

build_job:
  stage: build
  script:
    - npm run build
  cache:
    untracked: true
  only:
    - master
  tags:
    - master


test_job:
  stage: test
  script:
    - npm run test
  cache:
    untracked: true
  tags:
    - master
    - develop


deploy_job:
  stage: deploy
  script:
    - npm publish
  only:
    - master
  tags:
    - master

