stages:
- install
- test
- build

install_job:
    stage: install
    script:
    - npm install
    tags:
    - master

test_job:
    stage: test
    script:
    - npm run test
    tags:
    - master

build_job:
    stage: build
    script:
    - npm run build
    tags:
    - master