stages:
    - test
    - compile
before_script:
    - npm install --save-dev
    
test_job:
    stage: test
    script:
    - npm run test
    tags:
    - master

build_job:
    stage: compile
    script:

    - npm run build
    tags:
    - master
